// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgMrULY7GVgFFdf1SeK1nAB03SQA2_eCk',
    appId: '1:858173552428:web:0a80bd6c9f4b8001f1de89',
    messagingSenderId: '858173552428',
    projectId: 'authpart-3f1d3',
    authDomain: 'authpart-3f1d3.firebaseapp.com',
    storageBucket: 'authpart-3f1d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrnsP8q7fsvWG1BsVgeB-kkDYzg0Trqzs',
    appId: '1:858173552428:android:9a16e550f8ff2a29f1de89',
    messagingSenderId: '858173552428',
    projectId: 'authpart-3f1d3',
    storageBucket: 'authpart-3f1d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqpv2zRLr1uXzicpD3K4Nr_QtPpMpQWUM',
    appId: '1:858173552428:ios:762d424b55834711f1de89',
    messagingSenderId: '858173552428',
    projectId: 'authpart-3f1d3',
    storageBucket: 'authpart-3f1d3.appspot.com',
    iosClientId: '858173552428-vpi0pam8d13ohg66vpqnigufkpueuplk.apps.googleusercontent.com',
    iosBundleId: 'com.example.predictiveMaintenanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqpv2zRLr1uXzicpD3K4Nr_QtPpMpQWUM',
    appId: '1:858173552428:ios:aca6df6da0c8c9c9f1de89',
    messagingSenderId: '858173552428',
    projectId: 'authpart-3f1d3',
    storageBucket: 'authpart-3f1d3.appspot.com',
    iosClientId: '858173552428-2rsbo81c2pegl2ulv350no10aarfha4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.predictiveMaintenanceApp.RunnerTests',
  );
}
